/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: makoto (https://sketchfab.com/lu87813)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/air-jordan-1-a4b434181fbb48008ad460722fd53725
title: Air Jordan 1
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { GLTF, GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useLoader } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    shoe_shoe_0: THREE.Mesh
    shoelace_shoelace_0: THREE.Mesh
  }
  materials: {
    shoe: THREE.MeshStandardMaterial
    shoelace: THREE.MeshStandardMaterial
  }
}

export default function AirJordan(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const gltf = useLoader(GLTFLoader, "/outfits/airJordan.glb");
  const { nodes, materials } = gltf as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.5, 1]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.shoe_shoe_0.geometry} material={materials.shoe} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.shoelace_shoelace_0.geometry} material={materials.shoelace} />
          </group>
        </group>
      </group>
    </group>
  )
}

