/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: donlk (https://sketchfab.com/donlk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cat-shoe-left-83072c9d2cf54194a165897bc77196c1
title: Cat shoe - Left
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { GLTF, GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useLoader } from '@react-three/fiber'
import { getRandomColor } from '../dayCamp'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const gltf = useLoader(GLTFLoader, "/outfits/catShoe.glb");
  const { nodes, materials } = gltf as GLTFResult
  return (
    <group ref={group} {...props} onClick={(e) => {e.stopPropagation(); getRandomColor(materials.material_0 as THREE.MeshStandardMaterial)}} dispose={null}>
      <group position={[0.02, 0, 0]} rotation={[-Math.PI / 2, -0.04, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}
