/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Murat Can ÜNAL (https://sketchfab.com/nmuratcan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hat-aea2cbc8684c45cf885af4eb3b26ea9c
title: Hat
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial_1: THREE.Mesh
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Hat1: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/cowboyHat.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Hat1} />
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Hat1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cowboyHat.glb')
