/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kenprol (https://sketchfab.com/kenprol)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/models/c2a5343bf18949fc8d6815034ec7f87d
title: Leather shoes
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Plane050__0: THREE.Mesh
  }
  materials: {
    RootNode: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/leatherShoes.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[33.33, 53.72, 65.55]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Plane050__0.geometry} material={materials.RootNode} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/leatherShoes.glb')
