/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: oksana560 (https://sketchfab.com/oksana560)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/05709929d10741bdbb362025b59abfee
title: Футболка
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_38: THREE.Mesh
    Object_41: THREE.Mesh
    Object_44: THREE.Mesh
  }
  materials: {
    FRONT_756596: THREE.MeshStandardMaterial
    FRONT_756596_0: THREE.MeshStandardMaterial
    FRONT_756596_1: THREE.MeshStandardMaterial
    FRONT_756596_2: THREE.MeshStandardMaterial
    FRONT_756596_3: THREE.MeshStandardMaterial
    FRONT_756596_4: THREE.MeshStandardMaterial
    FRONT_756596_5: THREE.MeshStandardMaterial
    FRONT_756596_6: THREE.MeshStandardMaterial
    FRONT_756596_7: THREE.MeshStandardMaterial
    Material756804: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/womanTshirt.glb') as unknown as GLTFResult as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.FRONT_756596} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.FRONT_756596_0} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.FRONT_756596} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.FRONT_756596_1} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.FRONT_756596_2} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.FRONT_756596_2} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.FRONT_756596_2} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.FRONT_756596} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.FRONT_756596} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.FRONT_756596} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.FRONT_756596_3} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.FRONT_756596_4} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.FRONT_756596_5} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.FRONT_756596_6} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.FRONT_756596_7} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.FRONT_756596_7} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.FRONT_756596_7} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.FRONT_756596_7} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.Material756804} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.Material756804} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.Material756804} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/womanTshirt.glb')
