/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sucholudek (https://sketchfab.com/sucholudek)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/c048d51a2e9a4ee99262dc27058d8b9e
title: Cowboy Hat
*/

import React, { useRef } from 'react'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    hat01__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export default function Cowboyhat(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const gltf = useLoader(GLTFLoader, "/hats/cowboyhat.glb");
  const { nodes, materials } = gltf as GLTFResult
  return (
    <group ref={group} scale={[0.022,0.022,0.022]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group>
              <mesh geometry={nodes.hat01__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
