name: Build and deploy React Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.0
        uses: actions/setup-node@v2
        with:
          node-version: 12.0
      - name: npm build
        run: |
          npm run build
      - name: deploy to DigitalOcean VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          source: './build'
          target: '/var/www/wtow.xyz/html'
