name: Build and deploy React Application

env: 
  CI: false

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.22.0
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.0
      - name: npm build
        run: |
          npm install -f
          npm run build
      - name: deploy to DigitalOcean VPS
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          host: ${{secrets.SSH_HOST}}
          privateKey: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          local: 'build'
          remote: '/var/www/wtow.xyz/html/'
          recursive: true
          atomicPut: true
          dotfiles: true
