/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ostrich33 (https://sketchfab.com/gohean333)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/umbrella-3f077a88008241c5b81161536f2d4dfe
title: umbrella
*/

import React, { useRef, useState } from 'react'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import * as THREE from 'three'
import { getRandomColor } from '../dayCamp';

type GLTFResult = GLTF & {
  nodes: {
    umbrellahandle01_umbrellahandle_VRayMtl_0: THREE.Mesh
    umbrellahandle02_umbrellahandle_VRayMtl_0: THREE.Mesh
    umbrellapolySurface1_umbrellaumbrella_main_metal_VRayMtl_0: THREE.Mesh
    umbrellapolySurface3_umbrellaumbrella_main_metal_VRayMtl_0: THREE.Mesh
    umbrellatop_umbrella_umbrellaumbrella_main_metal_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_rainbow_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_001_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_001_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_002_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_002_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_003_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_003_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_004_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_004_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_005_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_005_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_006_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_006_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_007_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_007_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_01_008_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_02_008_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal01_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal02_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal03_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal04_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal05_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal06_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal07_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrellaMetal08_umbrellaumbrella_hood_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_ring_01_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_ring_02_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_001_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_001_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_001_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_002_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_002_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_002_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_003_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_003_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_003_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_004_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_004_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_004_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_005_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_005_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_005_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_006_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_006_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_006_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_007_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_007_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_007_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_wire_008_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_01_008_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
    umbrellaumbrella_metal_02_008_umbrellaumbrella_build_VRayMtl_0: THREE.Mesh
  }
  materials: {
    umbrellahandle_VRayMtl: THREE.MeshStandardMaterial
    umbrellaumbrella_main_metal_VRayMtl: THREE.MeshStandardMaterial
    umbrellaumbrella_hood_VRayMtl: THREE.MeshStandardMaterial
    umbrellaumbrella_build_VRayMtl: THREE.MeshStandardMaterial
  }
}

export default function Umbrella(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const gltf = useLoader(GLTFLoader, "/umbrella/umbrella.glb");
  const { nodes, materials } = gltf as GLTFResult

  return (
    <group onClick={(e) => {getRandomColor(materials.umbrellaumbrella_hood_VRayMtl as THREE.MeshStandardMaterial)}} ref={group} {...props} scale={[0.12, 0.12, 0.12]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <mesh
              material={materials.umbrellahandle_VRayMtl}
              geometry={nodes.umbrellahandle01_umbrellahandle_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellahandle_VRayMtl}
              geometry={nodes.umbrellahandle02_umbrellahandle_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_main_metal_VRayMtl}
              geometry={nodes.umbrellapolySurface1_umbrellaumbrella_main_metal_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_main_metal_VRayMtl}
              geometry={nodes.umbrellapolySurface3_umbrellaumbrella_main_metal_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_main_metal_VRayMtl}
              geometry={nodes.umbrellatop_umbrella_umbrellaumbrella_main_metal_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_rainbow_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_001_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_001_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_002_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_002_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_003_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_003_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_004_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_004_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_005_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_005_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_006_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_006_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_007_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_007_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_01_008_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_02_008_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal01_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal02_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal03_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal04_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal05_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal06_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal07_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_hood_VRayMtl}
              geometry={nodes.umbrellaumbrellaMetal08_umbrellaumbrella_hood_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_ring_01_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_ring_02_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_001_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_001_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_001_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_002_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_002_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_002_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_003_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_003_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_003_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_004_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_004_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_004_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_005_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_005_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_005_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_006_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_006_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_006_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_007_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_007_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_007_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_wire_008_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_01_008_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
            <mesh
              material={materials.umbrellaumbrella_build_VRayMtl}
              geometry={nodes.umbrellaumbrella_metal_02_008_umbrellaumbrella_build_VRayMtl_0.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  )
}